"use client"

import { useState } from "react"
import { X, Heart, Camera, Users, Calendar, Video } from "lucide-react"
import { galleryImages, galleryVideos } from "./_Images"
import { VideoThumbnail } from "../../components/ui/VideoThumbnail"

const categories = [
  { id: "all", name: "All Photos", icon: Camera },
  { id: "videos", name: "Videos", icon: Video },
  { id: "ceremony", name: "Ceremony", icon: Heart },
  { id: "portraits", name: "Portraits", icon: Users },
  { id: "reception", name: "Reception", icon: Calendar },
  { id: "details", name: "Details", icon: Camera },
]

export default function WeddingGallery() {
  const [selectedCategory, setSelectedCategory] = useState("all")
  const [selectedMedia, setSelectedMedia] = useState<number | null>(null)

  // Add src property to videos for consistency
  const videosWithThumbnails = galleryVideos.map((video) => ({
    ...video,
    src: "", // Will be generated by VideoThumbnail component
  }))

  const filteredMedia =
    selectedCategory === "all"
      ? [...galleryImages, ...videosWithThumbnails]
      : selectedCategory === "videos"
        ? videosWithThumbnails
        : galleryImages.filter((img) => img.category === selectedCategory)

  const openLightbox = (index: number) => {
    setSelectedMedia(index)
  }

  const closeLightbox = () => {
    setSelectedMedia(null)
  }

  const nextMedia = () => {
    if (selectedMedia !== null) {
      setSelectedMedia((selectedMedia + 1) % filteredMedia.length)
    }
  }

  const prevMedia = () => {
    if (selectedMedia !== null) {
      setSelectedMedia(selectedMedia === 0 ? filteredMedia.length - 1 : selectedMedia - 1)
    }
  }

  return (
    <div className="min-h-screen bg-white">
      {/* Hero Section */}
      <section className="relative h-[70vh] flex items-center justify-center overflow-hidden">
        <div
          className="absolute inset-0 bg-cover bg-center"
          style={{
            backgroundImage: `url('https://scontent.fccu3-1.fna.fbcdn.net/v/t39.30808-6/494714762_122137841480403744_2385635859063415468_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=127cfc&_nc_ohc=0CJy5RQlMTkQ7kNvwHYzN_1&_nc_oc=AdlALyAevkbNdBN8uMyvFkzfm576L5rKT2z5Zr1VbHafnrTCTiAxLCjz3P-JkxaiX54&_nc_zt=23&_nc_ht=scontent.fccu3-1.fna&_nc_gid=dxxDU9YJImjWYyFmEconbA&oh=00_AfIHEEqmTykPGB-80ClvPJHvD-uptU1lIRk9fTMQqwPrkQ&oe=683793DC')`,
          }}
        ></div>
        <div className="absolute inset-0 bg-black/40"></div>
        <div className="relative z-10 text-center px-4 max-w-4xl mx-auto">
          <h1 className="text-5xl md:text-7xl font-light text-white mb-6 tracking-wide drop-shadow-lg">
            Wedding
            <span className="block text-rose-300 font-serif italic">Collection</span>
          </h1>
          <p className="text-xl md:text-2xl text-white/90 font-light leading-relaxed drop-shadow-md">
            Capturing love stories through timeless photography
          </p>
          <div className="mt-8 flex justify-center">
            <div className="w-24 h-px bg-rose-300/70"></div>
          </div>
        </div>
      </section>

      {/* Category Filter */}
      <section className="py-12 px-4 bg-gray-50">
        <div className="max-w-6xl mx-auto">
          <div className="flex flex-wrap justify-center gap-4 mb-8">
            {categories.map((category) => {
              const IconComponent = category.icon
              return (
                <button
                  key={category.id}
                  onClick={() => setSelectedCategory(category.id)}
                  className={`flex items-center gap-2 px-6 py-3 rounded-full transition-all duration-300 ${
                    selectedCategory === category.id
                      ? "bg-rose-500 text-white shadow-lg transform scale-105"
                      : "bg-white text-gray-600 hover:bg-rose-50 hover:text-rose-500 shadow-md"
                  }`}
                >
                  <IconComponent size={18} />
                  <span className="font-medium">{category.name}</span>
                </button>
              )
            })}
          </div>
        </div>
      </section>

      {/* Gallery Grid */}
      <section className="py-12 px-4">
        <div className="max-w-7xl mx-auto">
          <div className="columns-1 sm:columns-2 lg:columns-3 xl:columns-4 gap-6 space-y-6">
            {filteredMedia.map((media, index) =>
              media.type === "video" ? (
                <VideoThumbnail
                  key={index}
                  videoSrc={media.videoSrc!}
                  alt={media.alt}
                  onClick={() => openLightbox(index)}
                />
              ) : (
                <div
                  key={index}
                  className="break-inside-avoid group cursor-pointer"
                  onClick={() => openLightbox(index)}
                >
                  <div className="relative overflow-hidden rounded-2xl shadow-lg hover:shadow-2xl transition-all duration-500 transform hover:scale-[1.02]">
                    <img
                      src={media.src || "/placeholder.svg"}
                      alt={media.alt}
                      className="w-full h-auto object-cover transition-transform duration-700 group-hover:scale-110"
                      loading="lazy"
                    />

                    <div className="absolute inset-0 bg-gradient-to-t from-black/50 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                      <div className="absolute bottom-4 left-4 text-white">
                        <p className="text-sm font-medium">{media.alt}</p>
                      </div>
                    </div>
                    <div className="absolute top-4 right-4 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                      <div className="bg-white/20 backdrop-blur-sm rounded-full p-2">
                        <Heart className="w-5 h-5 text-white" />
                      </div>
                    </div>
                  </div>
                </div>
              ),
            )}
          </div>
        </div>
      </section>

      {/* Lightbox */}
      {selectedMedia !== null && (
        <div className="fixed inset-0 z-50 bg-black/95 flex items-center justify-center p-4">
          <button
            onClick={closeLightbox}
            className="absolute top-6 right-6 text-white hover:text-rose-300 transition-colors z-10"
          >
            <X size={32} />
          </button>

          <button
            onClick={prevMedia}
            className="absolute left-6 top-1/2 transform -translate-y-1/2 text-white hover:text-rose-300 transition-colors z-10"
          >
            <div className="w-12 h-12 rounded-full bg-white/10 backdrop-blur-sm flex items-center justify-center">
              ←
            </div>
          </button>

          <button
            onClick={nextMedia}
            className="absolute right-6 top-1/2 transform -translate-y-1/2 text-white hover:text-rose-300 transition-colors z-10"
          >
            <div className="w-12 h-12 rounded-full bg-white/10 backdrop-blur-sm flex items-center justify-center">
              →
            </div>
          </button>

          <div className="max-w-4xl max-h-[90vh] flex items-center justify-center">
            {filteredMedia[selectedMedia].type === "video" ? (
              <video
                src={filteredMedia[selectedMedia].videoSrc}
                controls
                autoPlay
                className="max-w-full max-h-full rounded-lg"
                style={{ maxHeight: "80vh" }}
              >
                Your browser does not support the video tag.
              </video>
            ) : (
              <img
                src={filteredMedia[selectedMedia].src || "/placeholder.svg"}
                alt={filteredMedia[selectedMedia].alt}
                className="max-w-full max-h-full object-contain rounded-lg"
              />
            )}
          </div>

          <div className="absolute bottom-6 left-1/2 transform -translate-x-1/2 text-white text-center">
            <p className="text-lg font-medium mb-2">{filteredMedia[selectedMedia].alt}</p>
            <p className="text-sm opacity-75">
              {selectedMedia + 1} of {filteredMedia.length} •{" "}
              {filteredMedia[selectedMedia].type === "video" ? "Video" : "Photo"}
            </p>
          </div>
        </div>
      )}

      {/* Call to Action */}
      <section className="py-20 bg-gradient-to-r from-rose-50 to-pink-50">
        <div className="max-w-4xl mx-auto text-center px-4">
          <h2 className="text-4xl md:text-5xl font-light text-gray-800 mb-6">
            Ready to capture your
            <span className="text-rose-500 font-serif italic"> love story?</span>
          </h2>
          <p className="text-xl text-gray-600 mb-8 leading-relaxed">
            Lets create beautiful memories that will last a lifetime
          </p>
          <button className="bg-rose-500 text-white px-8 py-4 rounded-full text-lg font-medium hover:bg-rose-600 transition-colors duration-300 shadow-lg hover:shadow-xl transform hover:scale-105">
            Book Your Session
          </button>
        </div>
      </section>
    </div>
  )
}
